package com.rkfinserv.stockmarket.service;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;

@Service
public class ExcludedStocksService {
	
	
	
	public List<String> excludedList = List.of(
			"ABSLNN50ET",
			"IBMFNIFTY",
			"ICICI500",
			"ICICIALPLV",
			"ICICIBANKN",
			"ICICIBANKP",
			"ICICIGOLD",
			"ICICILIQ",
			"ICICILOVOL",
			"ICICIM150",
			"ICICIMCAP",
			"ICICINF100",
			"ICICINIFTY",
			"ICICINV20",
			"ICICINXT50",
			"ICICIPHARM",
			"IEX",
			"KOTAKBKETF",
			"KOTAKGOLD",
			"KOTAKIT",
			"KOTAKNIFTY",
			"KOTAKNV20",
			"KOTAKPSUBK",
			"M100",
			"MAN50ETF",
			"MANXT50",
			"NETF",
			"NETFCONSUM",
			"NETFDIVOPP",
			"NETFGILT5Y",
			"NETFIT",
			"NETFLTGILT",
			"NETFMID150",
			"NETFNIF100",
			"NETFNV20",
			"NETFSDL26",
			"NIFTYBEES",
			"NPBET",
			"UTIBANKETF",
			"UTINEXT50",
			"UTINIFTETF",
			"UTISENSETF",
			"UTISXN50",
			"SBIETFIT",
			"SBIETFPB",
			"SBIETFQLTY",
			"SETF10GILT",
			"SETFGOLD",
			"SETFNIF50",
			"SETFNIFBK",
			"SETFNN50",
			"SHARIABEES",
			"LTMFEOF2R",
			"M50",
			"LIQUIDETF",
			"LIQUIDBEES",
			"LICNETFGSC",
			"LICNETFN50",
			"LICNETFSEN",
			"LICNFNHGP",
			"MAESGETF",
			"MAFANG",
			"MAN50ETF",
			"MANXT50",
			"MC1RG",
			"N100",
			"NCPSESDL24",
			"QGOLDHALF",
			"QNIFTY",
			"PSUBNKBEES",
			"IVZINGOLD",
			"IVZINNIFTY",
			"INFRABEES",
			"IBMFNIFTY",
			"IDBIGOLD",
			"IDFNIFTYET",
			"HNGSNGBEES",
			"HDFCMFGETF",
			"HDFCNIFETF",
			"HDFCSENETF",
			"HBANKETF",
			"GOLDSHARE",
			"GOLDBEES",
			"G5",
			"FILDF2GPD",
			"FILDF2GP",
			"EQ30",
			"EBBETF0423",
			"EBBETF0425",
			"EBBETF0430",
			"EBBETF0431",
			"EBANK",
			"CPSEETF",
			"BSLNIFTY",
			"BSLGOLDETF",
			"BANKBEES",
			"AXISBNKETF",
			"AXISBPSETF",
			"AXISGOLD",
			"AXISHCETF",
			"AXISNIFTY",
			"AXISTECETF",
			"ABSLBANETF",
			"ABSLNN50ET",
			"ABSLRIF6RG",
			"ICICIB22",
			"ICICISENSX",
			"ICICITECH",
			"ICICISENSX",
			"ICICITECH",
			"JUNIORBEES"
			);

	public List<String> getExcludedList(){
		return excludedList;
	}
	
}
